name: payroute_desktop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
dependencies:
  http: ^1.0.0
  shared_preferences: ^2.0.0
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: ^6.1.2
  firebase_core: ^4.4.0
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Satoshi-BlackItalic
      fonts:
        - asset: assets/fonts/Satoshi-BlackItalic.otf

    - family: Satoshi-Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
    - family: Satoshi-BoldItalic
      fonts:
        - asset: assets/fonts/Satoshi-BoldItalic.otf
    - family: Satoshi-Regular
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
