import 'package:flutter/foundation.dart';

@immutable
class CountryEntry {
  final String code;
  final String name;
  /// E.164 country calling code **without** the leading "+" (e.g., "1", "234").
  final String dialCode;

  const CountryEntry({required this.code, required this.name, required this.dialCode});
}

/// A lightweight, dependency-free world country list for dropdowns.
///
/// Includes ISO-3166 alpha-2 codes + calling codes. Some territories share
/// calling codes (e.g. NANP = 1). This is intended for selection UX.
class CountryData {
  static const List<CountryEntry> all = <CountryEntry>[
    CountryEntry(code: 'AF', name: 'Afghanistan', dialCode: '93'),
    CountryEntry(code: 'AL', name: 'Albania', dialCode: '355'),
    CountryEntry(code: 'DZ', name: 'Algeria', dialCode: '213'),
    CountryEntry(code: 'AS', name: 'American Samoa', dialCode: '1'),
    CountryEntry(code: 'AD', name: 'Andorra', dialCode: '376'),
    CountryEntry(code: 'AO', name: 'Angola', dialCode: '244'),
    CountryEntry(code: 'AI', name: 'Anguilla', dialCode: '1'),
    CountryEntry(code: 'AQ', name: 'Antarctica', dialCode: ''),
    CountryEntry(code: 'AG', name: 'Antigua and Barbuda', dialCode: '1'),
    CountryEntry(code: 'AR', name: 'Argentina', dialCode: '54'),
    CountryEntry(code: 'AM', name: 'Armenia', dialCode: '374'),
    CountryEntry(code: 'AW', name: 'Aruba', dialCode: '297'),
    CountryEntry(code: 'AU', name: 'Australia', dialCode: '61'),
    CountryEntry(code: 'AT', name: 'Austria', dialCode: '43'),
    CountryEntry(code: 'AZ', name: 'Azerbaijan', dialCode: '994'),
    CountryEntry(code: 'BS', name: 'Bahamas', dialCode: '1'),
    CountryEntry(code: 'BH', name: 'Bahrain', dialCode: '973'),
    CountryEntry(code: 'BD', name: 'Bangladesh', dialCode: '880'),
    CountryEntry(code: 'BB', name: 'Barbados', dialCode: '1'),
    CountryEntry(code: 'BY', name: 'Belarus', dialCode: '375'),
    CountryEntry(code: 'BE', name: 'Belgium', dialCode: '32'),
    CountryEntry(code: 'BZ', name: 'Belize', dialCode: '501'),
    CountryEntry(code: 'BJ', name: 'Benin', dialCode: '229'),
    CountryEntry(code: 'BM', name: 'Bermuda', dialCode: '1'),
    CountryEntry(code: 'BT', name: 'Bhutan', dialCode: '975'),
    CountryEntry(code: 'BO', name: 'Bolivia', dialCode: '591'),
    CountryEntry(code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', dialCode: '599'),
    CountryEntry(code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '387'),
    CountryEntry(code: 'BW', name: 'Botswana', dialCode: '267'),
    CountryEntry(code: 'BR', name: 'Brazil', dialCode: '55'),
    CountryEntry(code: 'IO', name: 'British Indian Ocean Territory', dialCode: '246'),
    CountryEntry(code: 'BN', name: 'Brunei', dialCode: '673'),
    CountryEntry(code: 'BG', name: 'Bulgaria', dialCode: '359'),
    CountryEntry(code: 'BF', name: 'Burkina Faso', dialCode: '226'),
    CountryEntry(code: 'BI', name: 'Burundi', dialCode: '257'),
    CountryEntry(code: 'KH', name: 'Cambodia', dialCode: '855'),
    CountryEntry(code: 'CM', name: 'Cameroon', dialCode: '237'),
    CountryEntry(code: 'CA', name: 'Canada', dialCode: '1'),
    CountryEntry(code: 'CV', name: 'Cape Verde', dialCode: '238'),
    CountryEntry(code: 'KY', name: 'Cayman Islands', dialCode: '1'),
    CountryEntry(code: 'CF', name: 'Central African Republic', dialCode: '236'),
    CountryEntry(code: 'TD', name: 'Chad', dialCode: '235'),
    CountryEntry(code: 'CL', name: 'Chile', dialCode: '56'),
    CountryEntry(code: 'CN', name: 'China', dialCode: '86'),
    CountryEntry(code: 'CO', name: 'Colombia', dialCode: '57'),
    CountryEntry(code: 'KM', name: 'Comoros', dialCode: '269'),
    CountryEntry(code: 'CG', name: 'Congo (Republic of the)', dialCode: '242'),
    CountryEntry(code: 'CD', name: 'Congo (Democratic Republic of the)', dialCode: '243'),
    CountryEntry(code: 'CR', name: 'Costa Rica', dialCode: '506'),
    CountryEntry(code: 'CI', name: 'Côte d’Ivoire', dialCode: '225'),
    CountryEntry(code: 'HR', name: 'Croatia', dialCode: '385'),
    CountryEntry(code: 'CU', name: 'Cuba', dialCode: '53'),
    CountryEntry(code: 'CW', name: 'Curaçao', dialCode: '599'),
    CountryEntry(code: 'CY', name: 'Cyprus', dialCode: '357'),
    CountryEntry(code: 'CZ', name: 'Czechia', dialCode: '420'),
    CountryEntry(code: 'DK', name: 'Denmark', dialCode: '45'),
    CountryEntry(code: 'DJ', name: 'Djibouti', dialCode: '253'),
    CountryEntry(code: 'DM', name: 'Dominica', dialCode: '1'),
    CountryEntry(code: 'DO', name: 'Dominican Republic', dialCode: '1'),
    CountryEntry(code: 'EC', name: 'Ecuador', dialCode: '593'),
    CountryEntry(code: 'EG', name: 'Egypt', dialCode: '20'),
    CountryEntry(code: 'SV', name: 'El Salvador', dialCode: '503'),
    CountryEntry(code: 'GQ', name: 'Equatorial Guinea', dialCode: '240'),
    CountryEntry(code: 'ER', name: 'Eritrea', dialCode: '291'),
    CountryEntry(code: 'EE', name: 'Estonia', dialCode: '372'),
    CountryEntry(code: 'SZ', name: 'Eswatini', dialCode: '268'),
    CountryEntry(code: 'ET', name: 'Ethiopia', dialCode: '251'),
    CountryEntry(code: 'FJ', name: 'Fiji', dialCode: '679'),
    CountryEntry(code: 'FI', name: 'Finland', dialCode: '358'),
    CountryEntry(code: 'FR', name: 'France', dialCode: '33'),
    CountryEntry(code: 'GA', name: 'Gabon', dialCode: '241'),
    CountryEntry(code: 'GM', name: 'Gambia', dialCode: '220'),
    CountryEntry(code: 'GE', name: 'Georgia', dialCode: '995'),
    CountryEntry(code: 'DE', name: 'Germany', dialCode: '49'),
    CountryEntry(code: 'GH', name: 'Ghana', dialCode: '233'),
    CountryEntry(code: 'GR', name: 'Greece', dialCode: '30'),
    CountryEntry(code: 'GL', name: 'Greenland', dialCode: '299'),
    CountryEntry(code: 'GD', name: 'Grenada', dialCode: '1'),
    CountryEntry(code: 'GT', name: 'Guatemala', dialCode: '502'),
    CountryEntry(code: 'GN', name: 'Guinea', dialCode: '224'),
    CountryEntry(code: 'GW', name: 'Guinea-Bissau', dialCode: '245'),
    CountryEntry(code: 'GY', name: 'Guyana', dialCode: '592'),
    CountryEntry(code: 'HT', name: 'Haiti', dialCode: '509'),
    CountryEntry(code: 'HN', name: 'Honduras', dialCode: '504'),
    CountryEntry(code: 'HK', name: 'Hong Kong', dialCode: '852'),
    CountryEntry(code: 'HU', name: 'Hungary', dialCode: '36'),
    CountryEntry(code: 'IS', name: 'Iceland', dialCode: '354'),
    CountryEntry(code: 'IN', name: 'India', dialCode: '91'),
    CountryEntry(code: 'ID', name: 'Indonesia', dialCode: '62'),
    CountryEntry(code: 'IR', name: 'Iran', dialCode: '98'),
    CountryEntry(code: 'IQ', name: 'Iraq', dialCode: '964'),
    CountryEntry(code: 'IE', name: 'Ireland', dialCode: '353'),
    CountryEntry(code: 'IL', name: 'Israel', dialCode: '972'),
    CountryEntry(code: 'IT', name: 'Italy', dialCode: '39'),
    CountryEntry(code: 'JM', name: 'Jamaica', dialCode: '1'),
    CountryEntry(code: 'JP', name: 'Japan', dialCode: '81'),
    CountryEntry(code: 'JO', name: 'Jordan', dialCode: '962'),
    CountryEntry(code: 'KZ', name: 'Kazakhstan', dialCode: '7'),
    CountryEntry(code: 'KE', name: 'Kenya', dialCode: '254'),
    CountryEntry(code: 'KI', name: 'Kiribati', dialCode: '686'),
    CountryEntry(code: 'KP', name: 'North Korea', dialCode: '850'),
    CountryEntry(code: 'KR', name: 'South Korea', dialCode: '82'),
    CountryEntry(code: 'KW', name: 'Kuwait', dialCode: '965'),
    CountryEntry(code: 'KG', name: 'Kyrgyzstan', dialCode: '996'),
    CountryEntry(code: 'LA', name: 'Laos', dialCode: '856'),
    CountryEntry(code: 'LV', name: 'Latvia', dialCode: '371'),
    CountryEntry(code: 'LB', name: 'Lebanon', dialCode: '961'),
    CountryEntry(code: 'LS', name: 'Lesotho', dialCode: '266'),
    CountryEntry(code: 'LR', name: 'Liberia', dialCode: '231'),
    CountryEntry(code: 'LY', name: 'Libya', dialCode: '218'),
    CountryEntry(code: 'LI', name: 'Liechtenstein', dialCode: '423'),
    CountryEntry(code: 'LT', name: 'Lithuania', dialCode: '370'),
    CountryEntry(code: 'LU', name: 'Luxembourg', dialCode: '352'),
    CountryEntry(code: 'MO', name: 'Macao', dialCode: '853'),
    CountryEntry(code: 'MG', name: 'Madagascar', dialCode: '261'),
    CountryEntry(code: 'MW', name: 'Malawi', dialCode: '265'),
    CountryEntry(code: 'MY', name: 'Malaysia', dialCode: '60'),
    CountryEntry(code: 'MV', name: 'Maldives', dialCode: '960'),
    CountryEntry(code: 'ML', name: 'Mali', dialCode: '223'),
    CountryEntry(code: 'MT', name: 'Malta', dialCode: '356'),
    CountryEntry(code: 'MH', name: 'Marshall Islands', dialCode: '692'),
    CountryEntry(code: 'MR', name: 'Mauritania', dialCode: '222'),
    CountryEntry(code: 'MU', name: 'Mauritius', dialCode: '230'),
    CountryEntry(code: 'MX', name: 'Mexico', dialCode: '52'),
    CountryEntry(code: 'FM', name: 'Micronesia', dialCode: '691'),
    CountryEntry(code: 'MD', name: 'Moldova', dialCode: '373'),
    CountryEntry(code: 'MC', name: 'Monaco', dialCode: '377'),
    CountryEntry(code: 'MN', name: 'Mongolia', dialCode: '976'),
    CountryEntry(code: 'ME', name: 'Montenegro', dialCode: '382'),
    CountryEntry(code: 'MA', name: 'Morocco', dialCode: '212'),
    CountryEntry(code: 'MZ', name: 'Mozambique', dialCode: '258'),
    CountryEntry(code: 'MM', name: 'Myanmar', dialCode: '95'),
    CountryEntry(code: 'NA', name: 'Namibia', dialCode: '264'),
    CountryEntry(code: 'NR', name: 'Nauru', dialCode: '674'),
    CountryEntry(code: 'NP', name: 'Nepal', dialCode: '977'),
    CountryEntry(code: 'NL', name: 'Netherlands', dialCode: '31'),
    CountryEntry(code: 'NZ', name: 'New Zealand', dialCode: '64'),
    CountryEntry(code: 'NI', name: 'Nicaragua', dialCode: '505'),
    CountryEntry(code: 'NE', name: 'Niger', dialCode: '227'),
    CountryEntry(code: 'NG', name: 'Nigeria', dialCode: '234'),
    CountryEntry(code: 'NO', name: 'Norway', dialCode: '47'),
    CountryEntry(code: 'OM', name: 'Oman', dialCode: '968'),
    CountryEntry(code: 'PK', name: 'Pakistan', dialCode: '92'),
    CountryEntry(code: 'PA', name: 'Panama', dialCode: '507'),
    CountryEntry(code: 'PG', name: 'Papua New Guinea', dialCode: '675'),
    CountryEntry(code: 'PY', name: 'Paraguay', dialCode: '595'),
    CountryEntry(code: 'PE', name: 'Peru', dialCode: '51'),
    CountryEntry(code: 'PH', name: 'Philippines', dialCode: '63'),
    CountryEntry(code: 'PL', name: 'Poland', dialCode: '48'),
    CountryEntry(code: 'PT', name: 'Portugal', dialCode: '351'),
    CountryEntry(code: 'QA', name: 'Qatar', dialCode: '974'),
    CountryEntry(code: 'RO', name: 'Romania', dialCode: '40'),
    CountryEntry(code: 'RU', name: 'Russia', dialCode: '7'),
    CountryEntry(code: 'RW', name: 'Rwanda', dialCode: '250'),
    CountryEntry(code: 'SA', name: 'Saudi Arabia', dialCode: '966'),
    CountryEntry(code: 'SN', name: 'Senegal', dialCode: '221'),
    CountryEntry(code: 'RS', name: 'Serbia', dialCode: '381'),
    CountryEntry(code: 'SC', name: 'Seychelles', dialCode: '248'),
    CountryEntry(code: 'SL', name: 'Sierra Leone', dialCode: '232'),
    CountryEntry(code: 'SG', name: 'Singapore', dialCode: '65'),
    CountryEntry(code: 'SK', name: 'Slovakia', dialCode: '421'),
    CountryEntry(code: 'SI', name: 'Slovenia', dialCode: '386'),
    CountryEntry(code: 'SB', name: 'Solomon Islands', dialCode: '677'),
    CountryEntry(code: 'SO', name: 'Somalia', dialCode: '252'),
    CountryEntry(code: 'ZA', name: 'South Africa', dialCode: '27'),
    CountryEntry(code: 'SS', name: 'South Sudan', dialCode: '211'),
    CountryEntry(code: 'ES', name: 'Spain', dialCode: '34'),
    CountryEntry(code: 'LK', name: 'Sri Lanka', dialCode: '94'),
    CountryEntry(code: 'SD', name: 'Sudan', dialCode: '249'),
    CountryEntry(code: 'SR', name: 'Suriname', dialCode: '597'),
    CountryEntry(code: 'SE', name: 'Sweden', dialCode: '46'),
    CountryEntry(code: 'CH', name: 'Switzerland', dialCode: '41'),
    CountryEntry(code: 'SY', name: 'Syria', dialCode: '963'),
    CountryEntry(code: 'TW', name: 'Taiwan', dialCode: '886'),
    CountryEntry(code: 'TJ', name: 'Tajikistan', dialCode: '992'),
    CountryEntry(code: 'TZ', name: 'Tanzania', dialCode: '255'),
    CountryEntry(code: 'TH', name: 'Thailand', dialCode: '66'),
    CountryEntry(code: 'TG', name: 'Togo', dialCode: '228'),
    CountryEntry(code: 'TO', name: 'Tonga', dialCode: '676'),
    CountryEntry(code: 'TT', name: 'Trinidad and Tobago', dialCode: '1'),
    CountryEntry(code: 'TN', name: 'Tunisia', dialCode: '216'),
    CountryEntry(code: 'TR', name: 'Turkey', dialCode: '90'),
    CountryEntry(code: 'UG', name: 'Uganda', dialCode: '256'),
    CountryEntry(code: 'UA', name: 'Ukraine', dialCode: '380'),
    CountryEntry(code: 'AE', name: 'United Arab Emirates', dialCode: '971'),
    CountryEntry(code: 'GB', name: 'United Kingdom', dialCode: '44'),
    CountryEntry(code: 'US', name: 'United States', dialCode: '1'),
    CountryEntry(code: 'UY', name: 'Uruguay', dialCode: '598'),
    CountryEntry(code: 'UZ', name: 'Uzbekistan', dialCode: '998'),
    CountryEntry(code: 'VU', name: 'Vanuatu', dialCode: '678'),
    CountryEntry(code: 'VE', name: 'Venezuela', dialCode: '58'),
    CountryEntry(code: 'VN', name: 'Vietnam', dialCode: '84'),
    CountryEntry(code: 'YE', name: 'Yemen', dialCode: '967'),
    CountryEntry(code: 'ZM', name: 'Zambia', dialCode: '260'),
    CountryEntry(code: 'ZW', name: 'Zimbabwe', dialCode: '263'),
  ];

  static final Map<String, CountryEntry> _byCode = {for (final c in all) c.code: c};

  static CountryEntry? byCode(String code) => _byCode[code.toUpperCase()];
}
