// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__JP2xhb0R8FyB00YKQDshaK0k8udIcg',
    appId: '1:940977436456:web:8b1a5e14ed3cfa3664421d',
    messagingSenderId: '940977436456',
    projectId: 'rqr88qtom5amftxo8feci8jvycmnx5',
    authDomain: 'rqr88qtom5amftxo8feci8jvycmnx5.firebaseapp.com',
    storageBucket: 'rqr88qtom5amftxo8feci8jvycmnx5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA6CIqFPKaHXJc9vrS_UTzjAa5KuLt-z4',
    appId: '1:940977436456:android:27990c1b3f145a0a64421d',
    messagingSenderId: '940977436456',
    projectId: 'rqr88qtom5amftxo8feci8jvycmnx5',
    storageBucket: 'rqr88qtom5amftxo8feci8jvycmnx5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwG2vVEcnfbOyPW2b-ATsUGsy6OrESME',
    appId: '1:940977436456:ios:88ad23854491ecd264421d',
    messagingSenderId: '940977436456',
    projectId: 'rqr88qtom5amftxo8feci8jvycmnx5',
    storageBucket: 'rqr88qtom5amftxo8feci8jvycmnx5.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
